name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypdns

      - name: Compile code
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake
            mkdir -p build
            cd build
            cmake ..
            make
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            # Add Windows build steps here
            echo "Windows build steps needed"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            # Add macOS build steps here
            echo "macOS build steps needed"
          fi

      - name: Update version and changelog
        run: python update_version_changelog.py

      - name: Create and push a new release
        if: github.ref == 'refs/heads/master'
        run: |
          git config --global user.name "${{ secrets.GH_USER }}"
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git add version.h CHANGELOG.md
          git commit -m "Release ${{ steps.update_version_changelog.outputs.version }}"
          git tag -a "v${{ steps.update_version_changelog.outputs.version }}" -m "Release ${{ steps.update_version_changelog.outputs.version }}"
          git push origin --tags
          git push origin master